pipeline {
  agent {
    node {
    image 'mcr.microsoft.com/dotnet/sdk'
    args '-p 3000:3000 -p 5000:5000'
    }
  }
  stages {
    stage('Npm Install') {
      steps {
        // npm install @angular/cli
        // cd "AutoAPI"/ClientApp
        // npm install
        sh 'echo "Installing..."'
      }
    }

    stage('Build Production Mode') {
      when {
            branch 'master'
       }
       steps {
          // cd "AutoAPI"/ClientApp
          // npm run "build"
          sh 'echo "Building on master'
       }

       when {
            branch 'TEST'
       }
       steps {
          // cd "AutoAPI"/ClientApp
          // npm run "build"
          sh 'echo "Building on test'
       }
     }
   }
 }
