pipeline {
  agent {
    dockerfile {
      filename 'Dockerfile'
      args '-p 3000:3000 -p 5000:5000 --name ' + env.BRANCH_NAME + 'env -i --entrypoint='
    }
  }
  tools { nodejs "redwaneJS" }
  stages {
    stage('Deploy to production enviroment'){
     when {
            branch 'master'
       }
       steps {
          input message: 'Project has been successfully deployed in a container named ' + env.BRANCH_NAME + 'env'
       }
     }

    stage('Deploy to test enviroment'){
     when {
            branch 'test'
       }
       steps {
         input message: 'Project has been successfully deployed in a container named ' + env.BRANCH_NAME + 'env'
       }
     }
   }
 }
